# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'PAGPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'LXYPAGPlayerSDK', :git => 'https://github.com/liang1520912/LXYPAG.git'
  pod 'LookinServer', '1.0.0', :configurations => ['Debug']
end
