# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_modular_headers!
target 'PAGPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!

  pod 'LXYPAGPlayerSDK', :git => 'https://github.com/liang1520912/LXYPAG.git'
  pod 'LookinServer', '1.0.0', :configurations => ['Debug']
end
post_install do |installer|
   
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          config.build_settings['DEVELOPMENT_TEAM'] = 'JH9589JWJG'
      end
  end
  
end